import 'package:shapeshred/features/nutrition/domain/models/food.dart';

class FoodRepository {
  static final List<Food> foods = [
    // Proteins
    Food(
      id: 'chicken_breast',
      name: 'Chicken Breast',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 165,
      protein: 31.0,
      carbs: 0.0,
      fat: 3.6,
      fiber: 0.0,
      sugar: 0.0,
      category: 'Protein',
    ),
    Food(
      id: 'salmon',
      name: 'Salmon',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 208,
      protein: 20.0,
      carbs: 0.0,
      fat: 13.0,
      fiber: 0.0,
      sugar: 0.0,
      category: 'Protein',
    ),
    Food(
      id: 'eggs',
      name: 'Eggs',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 155,
      protein: 13.0,
      carbs: 1.1,
      fat: 11.0,
      fiber: 0.0,
      sugar: 1.1,
      category: 'Protein',
    ),
    Food(
      id: 'greek_yogurt',
      name: 'Greek Yogurt',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 59,
      protein: 10.0,
      carbs: 3.6,
      fat: 0.4,
      fiber: 0.0,
      sugar: 3.6,
      category: 'Protein',
    ),
    Food(
      id: 'tuna',
      name: 'Tuna',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 116,
      protein: 26.0,
      carbs: 0.0,
      fat: 1.0,
      fiber: 0.0,
      sugar: 0.0,
      category: 'Protein',
    ),
    Food(
      id: 'beef_lean',
      name: 'Lean Beef',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 250,
      protein: 26.0,
      carbs: 0.0,
      fat: 15.0,
      fiber: 0.0,
      sugar: 0.0,
      category: 'Protein',
    ),

    // Carbohydrates
    Food(
      id: 'brown_rice',
      name: 'Brown Rice',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 111,
      protein: 2.6,
      carbs: 23.0,
      fat: 0.9,
      fiber: 1.8,
      sugar: 0.4,
      category: 'Carbohydrates',
    ),
    Food(
      id: 'oats',
      name: 'Oats',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 389,
      protein: 16.9,
      carbs: 66.0,
      fat: 6.9,
      fiber: 10.6,
      sugar: 0.6,
      category: 'Carbohydrates',
    ),
    Food(
      id: 'sweet_potato',
      name: 'Sweet Potato',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 86,
      protein: 1.6,
      carbs: 20.0,
      fat: 0.1,
      fiber: 3.0,
      sugar: 4.2,
      category: 'Carbohydrates',
    ),
    Food(
      id: 'quinoa',
      name: 'Quinoa',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 120,
      protein: 4.4,
      carbs: 21.0,
      fat: 1.9,
      fiber: 2.8,
      sugar: 0.9,
      category: 'Carbohydrates',
    ),
    Food(
      id: 'whole_wheat_bread',
      name: 'Whole Wheat Bread',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 247,
      protein: 13.0,
      carbs: 41.0,
      fat: 3.4,
      fiber: 7.0,
      sugar: 5.0,
      category: 'Carbohydrates',
    ),
    Food(
      id: 'pasta',
      name: 'Pasta',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 131,
      protein: 5.0,
      carbs: 25.0,
      fat: 1.1,
      fiber: 2.5,
      sugar: 0.6,
      category: 'Carbohydrates',
    ),

    // Vegetables
    Food(
      id: 'broccoli',
      name: 'Broccoli',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 34,
      protein: 2.8,
      carbs: 7.0,
      fat: 0.4,
      fiber: 2.6,
      sugar: 1.5,
      category: 'Vegetables',
    ),
    Food(
      id: 'spinach',
      name: 'Spinach',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 23,
      protein: 2.9,
      carbs: 3.6,
      fat: 0.4,
      fiber: 2.2,
      sugar: 0.4,
      category: 'Vegetables',
    ),
    Food(
      id: 'carrots',
      name: 'Carrots',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 41,
      protein: 0.9,
      carbs: 10.0,
      fat: 0.2,
      fiber: 2.8,
      sugar: 4.7,
      category: 'Vegetables',
    ),
    Food(
      id: 'avocado',
      name: 'Avocado',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 160,
      protein: 2.0,
      carbs: 8.5,
      fat: 15.0,
      fiber: 6.7,
      sugar: 0.7,
      category: 'Vegetables',
    ),
    Food(
      id: 'tomatoes',
      name: 'Tomatoes',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 18,
      protein: 0.9,
      carbs: 3.9,
      fat: 0.2,
      fiber: 1.2,
      sugar: 2.6,
      category: 'Vegetables',
    ),
    Food(
      id: 'bell_peppers',
      name: 'Bell Peppers',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 31,
      protein: 1.0,
      carbs: 6.0,
      fat: 0.3,
      fiber: 2.1,
      sugar: 4.2,
      category: 'Vegetables',
    ),

    // Fruits
    Food(
      id: 'apple',
      name: 'Apple',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 52,
      protein: 0.3,
      carbs: 14.0,
      fat: 0.2,
      fiber: 2.4,
      sugar: 10.0,
      category: 'Fruits',
    ),
    Food(
      id: 'banana',
      name: 'Banana',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 89,
      protein: 1.1,
      carbs: 23.0,
      fat: 0.3,
      fiber: 2.6,
      sugar: 12.0,
      category: 'Fruits',
    ),
    Food(
      id: 'berries',
      name: 'Mixed Berries',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 57,
      protein: 0.7,
      carbs: 14.0,
      fat: 0.3,
      fiber: 2.4,
      sugar: 7.0,
      category: 'Fruits',
    ),
    Food(
      id: 'orange',
      name: 'Orange',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 47,
      protein: 0.9,
      carbs: 12.0,
      fat: 0.1,
      fiber: 2.4,
      sugar: 9.0,
      category: 'Fruits',
    ),
    Food(
      id: 'grapes',
      name: 'Grapes',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 69,
      protein: 0.7,
      carbs: 18.0,
      fat: 0.2,
      fiber: 0.9,
      sugar: 16.0,
      category: 'Fruits',
    ),

    // Dairy
    Food(
      id: 'milk',
      name: 'Milk (2%)',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'ml',
      calories: 50,
      protein: 3.3,
      carbs: 4.8,
      fat: 2.0,
      fiber: 0.0,
      sugar: 4.8,
      category: 'Dairy',
    ),
    Food(
      id: 'cheese',
      name: 'Cheddar Cheese',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 403,
      protein: 25.0,
      carbs: 1.3,
      fat: 33.0,
      fiber: 0.0,
      sugar: 0.5,
      category: 'Dairy',
    ),
    Food(
      id: 'cottage_cheese',
      name: 'Cottage Cheese',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 98,
      protein: 11.0,
      carbs: 3.4,
      fat: 4.3,
      fiber: 0.0,
      sugar: 2.7,
      category: 'Dairy',
    ),

    // Nuts & Seeds
    Food(
      id: 'almonds',
      name: 'Almonds',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 579,
      protein: 21.0,
      carbs: 22.0,
      fat: 50.0,
      fiber: 12.5,
      sugar: 4.4,
      category: 'Nuts & Seeds',
    ),
    Food(
      id: 'walnuts',
      name: 'Walnuts',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 654,
      protein: 15.0,
      carbs: 14.0,
      fat: 65.0,
      fiber: 6.7,
      sugar: 2.6,
      category: 'Nuts & Seeds',
    ),
    Food(
      id: 'peanut_butter',
      name: 'Peanut Butter',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 588,
      protein: 25.0,
      carbs: 20.0,
      fat: 50.0,
      fiber: 8.0,
      sugar: 10.0,
      category: 'Nuts & Seeds',
    ),

    // Snacks
    Food(
      id: 'protein_bar',
      name: 'Protein Bar',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 350,
      protein: 20.0,
      carbs: 30.0,
      fat: 10.0,
      fiber: 5.0,
      sugar: 15.0,
      category: 'Snacks',
    ),
    Food(
      id: 'dark_chocolate',
      name: 'Dark Chocolate (70%)',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 598,
      protein: 7.8,
      carbs: 46.0,
      fat: 43.0,
      fiber: 11.0,
      sugar: 24.0,
      category: 'Snacks',
    ),
    Food(
      id: 'popcorn',
      name: 'Popcorn (Air-popped)',
      brand: 'Generic',
      servingSize: 100,
      servingUnit: 'g',
      calories: 387,
      protein: 13.0,
      carbs: 78.0,
      fat: 4.0,
      fiber: 15.0,
      sugar: 0.9,
      category: 'Snacks',
    ),
  ];

  static List<Food> getByCategory(String category) {
    return foods.where((f) => f.category == category).toList();
  }

  static List<Food> search(String query) {
    final lowerQuery = query.toLowerCase();
    return foods.where((f) =>
        f.name.toLowerCase().contains(lowerQuery) ||
        f.brand.toLowerCase().contains(lowerQuery)
    ).toList();
  }

  static Food? getById(String id) {
    try {
      return foods.firstWhere((f) => f.id == id);
    } catch (e) {
      return null;
    }
  }

  static List<String> get categories => [
    'Protein',
    'Carbohydrates',
    'Vegetables',
    'Fruits',
    'Dairy',
    'Nuts & Seeds',
    'Snacks',
  ];
}
