// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcjYRX3rOeL2GERvVdeosyLMOrnfjDau0',
    appId: '1:796172535933:web:f3e964b4cd7c0df98a0914',
    messagingSenderId: '796172535933',
    projectId: 'shapeshred-858c5',
    authDomain: 'shapeshred-858c5.firebaseapp.com',
    storageBucket: 'shapeshred-858c5.firebasestorage.app',
    measurementId: 'G-98M9CTDPL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA83v1dJ2wHmd_HRcXZInd8yhdWRoMfBow',
    appId: '1:796172535933:android:ce32d475020462628a0914',
    messagingSenderId: '796172535933',
    projectId: 'shapeshred-858c5',
    storageBucket: 'shapeshred-858c5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDklqmUFLD2Yl6i4Wsak3Sv_8iB55PPU9U',
    appId: '1:796172535933:ios:b3a7d244951383648a0914',
    messagingSenderId: '796172535933',
    projectId: 'shapeshred-858c5',
    storageBucket: 'shapeshred-858c5.firebasestorage.app',
    androidClientId:
        '796172535933-6u5bbncacm3v8ncdoscdvhv17l2tn4gn.apps.googleusercontent.com',
    iosBundleId: 'yes',
  );
}
